
```{=html}
<style>
  body{text-align: justify}
</style>
```



::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

# CTB - CAP XV
## Das Infrações


### **ITEM 1:** 

A fiscalização por videomonitoramento flagrou um veículo ultrapassando outro veículo pelo acostamento, tendo transitado pelo acostamento para realizar a manobra. Durante a lavratura do auto de infração de trânsito (AIT), o Agente de Trânsito identificou duas condutas infracionais, a primeira foi o fato de o veículo ultrapassar outro veículo pelo acostamento (art. 202, do CTB) e a segunda, a prática da infração de transitar com o veículo pelo acostamento (art. 193, do CTB), tendo lavrado apenas 01 (um) AIT, relativo à infração de ultrapassar pelo acostamento. O Agente não lavrou o segundo AIT, referente à infração do artigo 193, do CTB, com base na definição de infrações:

1. Concomitantes
2. Sucessivas
3. Continuadas
4. Concorrentes
5. Condicionadas

::: {.callout-tip collapse="true"}
"**Gabarito :  4**".
:::

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


### **ITEM 2:** 

Ao realizar um patrulhamento viário de rotina, com o objetivo de garantir a segurança viária, os Agentes de Trânsito da AMC flagram um veículo avançando o sinal vermelho do semáforo. Ao realizarem o acompanhamento com a viatura, o mesmo veículo avança os sinais vermelhos dos semáforos de outros três cruzamentos consecutivos, totalizando quatro infrações iguais, relativas ao avanço de sinal vermelho do semáforo, regulamentada no artigo 208, do CTB, lavradas pelos Agentes. De acordo com o Manual Brasileiro de Fiscalização de Trânsito, os autos foram lavrados com base na definição de infrações:


1. Concorrentes
2. Continuadas
3. Sucessivas
4. Concomitantes
5. Condicionadas

::: {.callout-tip collapse="true"}
"**Gabarito :  4**".
:::

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


### **ITEM 3:** 

O Agente da Autoridade de Trânsito deve priorizar suas ações no sentido de coibir a prática das infrações de trânsito, devendo tratar a todos com urbanidade e respeito, sem, contudo, omitir-se das providências que a lei lhe determina. Logo, ao constatar o cometimento da infração, deverá:


1. Lavrar o respectivo auto e adotar as medidas penais cabíveis.
2. Aplicar a multa e as penalidades previstas no Código de
Trânsito Brasileiro.
3. Remover o veículo quando não for possível sanar a falha no
local da infração.
4. Apreender o veículo não sendo efetuada a regularização no
prazo determinado.
5. Lavrar o respectivo auto e adotar as medidas administrativas
e penais cabíveis


::: {.callout-tip collapse="true"}
"**Gabarito :  5**".
:::

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


### **ITEM 4:** 


As crianças com idade inferior a
_____________ anos que não tenham atingido
________________________ de altura devem
ser transportadas nos bancos traseiros, em
dispositivo de retenção adequado para cada
idade, peso e altura, salvo exceções
relacionadas a tipos específicos de veículos
regulamentadas pelo Contran. Escolha a
opção que preenche corretamente e
respectivamente as lacunas deixadas no
texto:

1. ( ) 07 (sete), 1,30 m (um metro e trinta
centímetros).
2. ( ) 08 (oito), 1,40 m (um metro e quarenta
centímetros).
3. ( ) 10 (dez), 1,45 m (um metro e quarenta e
cinco centímetros).
4. ( ) 11 (onze), 1,50 m (um metro e cinquenta
centímetros).
5. ( ) 12 (doze), 1,60 m (um metro e sessenta
centímetros).



::: {.callout-tip collapse="true"}
"**Gabarito : 3**".
:::

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


### **ITEM 5:** 

Complete a lacuna de acordo com as Resoluções do Conselho Nacional de Trânsito.

_______________ documento que dá início ao
processo administrativo para imposição de
punição, em decorrência de alguma infração à
legislação de trânsito;

1. ( ) Notificação da Autuação (NA).
2. ( ) Auto de Infração de Trânsito (AIT).
3. ( ) Notificação da Penalidade (NP).
4. ( ) Òrgão autuador.
5. ( ) Òrgão arrecadador.


::: {.callout-tip collapse="true"}
"**Gabarito :  2**".
:::

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


### **ITEM 6:** 

Complete a lacuna de acordo com as Resoluções
do Conselho Nacional de Trânsito.


____________ procedimento que dá ciència ao
proprietário do veículo de que foi cometida uma
infração de trânsito com seu veículo;

1. ( ) Auto de Infração de Trânsito (AIT)
2. ( ) Notificação da Infração (NI)
3. ( ) CONTRAN
4. ( ) Notificação da Penalidade (NP)
5. ( ) Notificação da Autuação (NA)


::: {.callout-tip collapse="true"}
"**Gabarito :  5**".
:::

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


### **ITEM 7:** 

O Agente de Trânsito tem como responsabilidade, dentre outras, exercer poder de Polícia de Trânsito, desenvolver atividades destinadas à melhoria da circulação, atuando como facilitador da mobilidade urbana ou rodoviária, baseando seu trabalho, dentre outras, nos princípios da legalidade, impessoalidade, moralidade, publicidade e eficiência, sendo suas atribuições, exceto:

1. ( ) Lavrar autos de infração no exercício das atividades
de fiscalização de trânsito e transporte incluindo a
fiscalização eletrônica, com base no Código de
Trânsito Brasileiro, legislações municipais e
normativas complementares.
2. ( ) Utilizar-se dos instrumentos de trabalho, conduzir
veículos e motocicletas, quando habilitado e
autorizado, no estrito exercício das atribuições do
cargo.
3. ( ) Efetuar levantamento de sinistros independente de
estar investido da função.
3. ( ) Desenvolver atividades de monitoramento do tráfego
de veículos e operação de trânsito.


::: {.callout-tip collapse="true"}
"**Gabarito :  3**".
:::

::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


