
```{=html}
<style>
  body{text-align: justify}
</style>
```


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::
  
  
# CTB - CAP XIX
## Dos Crimes de Trânsito


### **ITEM 1:** 
  
O Art. 165 do Código de Trânsito Brasileiro determina a natureza da infração, a penalidade e as medidas administrativas relativas a dirigir sob a influência de álcool ou de qualquer outra substância psicoativa que determine dependência. Nessa condição, ao condutor que infringiu esse artigo, será aplicada como penalidade:

1. ( ) multa, com fator multiplicador de 10, apenas.
2. ( ) suspensão do direito de dirigir por 12 meses, apenas.
3. ( ) multa, com fator multiplicador de 10, e suspensão do direito de dirigir por 12 meses.
4. ( ) recolhimento do documento de habilitação, apenas.
5. ( ) recolhimento do documento de habilitação e retenção do
veículo.


::: {.callout-tip collapse="true"}
"**Gabarito :  3**".
:::


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::  
  
  

### **ITEM 2:**  
  
É considerada crime de trânsito a condução de veículo automotor com capacidade psicomotora alterada em razão da influência de álcool.

Essa conduta pode ser constatada observando-se uma
concentração da substância, em etilômetro e descontando-se o
erro máximo admissível do medidor, igual ou superior a  

1. 0.00mg/L.
2. 0.18mg/L.
3. 0.34dg/L.
4. 0.34mg/L.
5. 0.68dg/L.


::: {.callout-tip collapse="true"}
"**Gabarito :  4**".
:::


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

### **ITEM 3:**  

No atendimento de um sinistro de trânsito, os Agentes do órgão municipal de trânsito verificaram que o condutor de um dos veículos envolvidos apresentava sinais de alteração da capacidade psicomotora, confirmada posteriormente por meio do teste de etilômetro, que registrou uma medição igual a 0,33 miligrama de álcool por litro de ar alveolar expirado (0,33 mg/L), descontado o erro máximo admissível.

Escreva V ou F, conforme seja verdadeiro ou falso o que se afirmar nos itens abaixo:

1. ( ) Foi caracterizado, no caso citado acima, o crime previsto no artigo 306, do CTB: Conduzir veículo automotor com capacidade psicomotora alterada em razão da influência de álcool ou de outra substância psicoativa que determine dependência.
2. ( ) Houve o cometimento da infração prevista no artigo 165, do CTB: Dirigir sob a influência de álcool ou de qualquer outra substância psicoativa que determine dependência; no caso do condutor do veículo que se submeteu ao teste do etilômetro.
3. ( ) As penas previstas no artigo 306, do CTB, são detenção, de seis meses a três anos, multa e suspensão ou proibição de se obter a permissão ou a habilitação para dirigir veículo automotor.
4. ( ) A infração do artigo 165 tem como penalidades a multa (dez vezes) e suspensão do direito de dirigir por 12 (doze) meses.

Está correta, de cima para baixo, a seguinte sequência:

1. ( ) F, V, V, F.
2. ( ) V, V, F, V.
3. ( ) F, V, V, V.
4. ( ) V, F, V, V.



::: {.callout-tip collapse="true"}
"**Gabarito :  3**".
:::


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


### **ITEM 4:**  


Considere a situação hipotética narrada a seguir para responder às próximas duas questões:

João saiu embriagado de um bar e passou a
dirigir seu Corcel II 1979 com som em alto volume
pela avenida principal de sua cidade. Alguns
quilômetros à frente, João avistou James, um
cidadão inglês desafeto seu, transitando por uma
calçada e, com o intento de tirar-lhe a vida, acelerou
e jogou o carro contra o homem, que veio a falecer
três horas depois, no hospital, em decorrência das
lesões do impacto.

#### **ITEM 4.1:**  

De acordo com as disposições do **Código de Trânsito Brasileiro**,
assinale a alternativa correta:


1. ( ) Considera-se praticado o crime por João no momento do falecimento da vítima, três horas depois do atropelamento.
2. ( ) Em razão de a vítima ter nacionalidade inglesa, aplicar-se-á sobre o caso a lei penal inglesa.
3. ( ) Se caso João se arrependesse de sua intenção a tempo de manobrar ou frear o carro, evitando, com isso, o falecimento de James, continuaria a responder pelos atos praticados e pelos incompletos.
4. ( ) De acordo com a situação narrada, João responderá por crime doloso.
5. ( ) De acordo com a situação narrada, João responderá por crime culposo.



::: {.callout-tip collapse="true"}
"**Gabarito :  5**".
:::


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


#### **ITEM 4.2:**  

De acordo com as disposições do **Código de Processo Penal**, assinale a alternativa correta:


1. ( ) Caso o Ministério Público não promova a ação penal contra João no prazo legal, aquele a quem couber representar James poderá promover ação privada no prazo de 2 (dois) anos, a contar do dia em que se esgotar o prazo para o oferecimento da denúncia.
2. ( ) Uma vez iniciada a ação penal contra João, cabe ao Ministério Público decidir se a continua ou dela desiste a qualquer momento.
3. D) É vedado o arquivamento do inquérito policial, em qualquer hipótese.
4. ( ) Em razão do falecimento de James, o direito de
representá-lo passará ao seu cônjuge, ascendente,
descendente ou irmão.
5. ( ) João poderá ser beneficiado por acordo de
não persecução penal, pois este tipo de acordo pode
ser realizado sempre que o Ministério Público
entender conveniente, independente do crime
praticado.


::: {.callout-tip collapse="true"}
"**Gabarito :  4**".
:::


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


### **ITEM 5:**  

Aos crimes cometidos na direção de veículos automotores previstos no CTB aplicam-se subsidiariamente as normas gerais do Código Penal, do Código de Processo Penal, bem como a Lei nº 9.099/1995, no que couber. A respeito das
disposições legais sobre os crimes de trânsito, julgue os itens de 1 a 5

1. ( ) A utilização de veículo sem placa ou com placa falsa é uma circunstância que sempre agrava a penalidade do crime de trânsito.
2. ( ) O condutor de veículo que, por ocasião de sinistro, deixa de prestar socorro à vítima ou não solicita auxílio da autoridade pública, exime-se do crime de trânsito caso comprove uma justa causa para a omissão.
3. ( ) Nos casos de homicídio culposo cometido na direção de veículo automotor, a pena pode ser duplicada caso o agente não possua CNH ou permissão para dirigir.
4. ( ) A prática que consiste em trafegar em velocidade incompatível com a segurança nas imediações de escolas, gerando perigo de dano, configura crime de trânsito sujeito a pena de detenção de seis meses a um ano, ou multa.
5. ( ) A modificação deliberada do estado de um veículo envolvido em um acidente automobilístico com vítima, com o propósito de induzir a erro o agente policial, constitui uma circunstância agravante nos crimes de trânsito, resultando em aumento da pena.


::: {.callout-tip collapse="true"}
"**Gabarito :  C-E-E-C-E**".
:::


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::
