

```{=html}
<style>
body{text-align: justify}
</style>
```


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


# CTB - CAP III
## Das Normas Gerais de Circulação e Conduta


### **ITEM 1:** 

Com relação às normas gerais de circulação e conduta estabelecidas pelo CTB, julgue os itens de 1 a 5 em **Certo** e **Errado**.

1. Quando dois veículos, trafegando por fluxos que se cruzem e se aproximando de uma rotatória não sinalizada, o veículo que já estiver circulando na rotatória terá preferência.
2. A circulação de veículos em passeios e calçadas é permitida apenas para acessar ou sair de imóveis, sendo considerada uma infração grave caso ocorra de maneira não autorizada.
3. A ultrapassagem de um veículo em movimento deve ser realizada pela direita, a menos que o veículo à frente esteja indicando a intenção de virar à direita.
4. Antes de realizar uma mudança lateral, o condutor deve ativar a luz indicadora de direção do veículo, sendo proibido utilizar gestos ou movimentos de braço para essa finalidade.
5. O condutor que estiver prestes a entrar em uma via, vindo de um terreno adjacente a essa via, deve ceder a preferência aos veículos e pedestres que estejam transitando nela.

::: {.callout-tip collapse="true"}
"**Gabarito :  **".
:::


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::


### **ITEM 2:** 

O Código de Trânsito Brasileiro, Lei n. 9.503, de 23 de setembro de 1997, estabelece, em capítulo próprio, normas gerais de circulação e conduta. Considerando o disposto no código em pauta, analise as afirmativas a seguir e dê valores Verdadeiro (V) ou Falso (F).


1. O condutor de veículo poderá fazer uso de buzina, desde que em toque breve e fora das áreas urbanas, quando for conveniente advertir a um condutor que se tem o propósito de ultrapassá-lo.
2. O Código de Trânsito Brasileiro veda
expressamente o transporte de passageiros de
motocicletas, motonetas e ciclomotores em
carro lateral acoplado aos veículos.
3. A autoridade de trânsito com circunscrição sobre
a via poderá autorizar a circulação de bicicletas
no sentido contrário ao fluxo dos veículos
automotores, desde que dotado o trecho com
ciclofaixa.
4. É livre a circulação de bicicletas nos passeios


Assinale a alternativa que apresenta a
sequência correta de cima para baixo.

1. ( ) V-V-V-V
2. ( ) F-V-F-V
3. ( ) V-F-V-F
4. ( ) F-F-V-V


::: {.callout-tip collapse="true"}
"**Gabarito :  3**".
:::


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::

### **ITEM 3:** 

Com base no Artigo 130 do CÛdigo de Trânsito Brasileiro, qual categoria de veículo está isenta do licenciamento anual, de acordo com o órgão executivo de trànsito do Estado ou do Distrito Federal onde o veículo está registrado? 

1. ( ) Veículos de transporte público.
2. ( ) Veículos automotores.
3. ( ) Veículos de uso bélico.
4. ( ) Reboques.
5. ( ) Veículos de transferência de residência.



::: {.callout-tip collapse="true"}
"**Gabarito :  3**".
:::


::: progress
::: {.progress-bar style="width: 100%;"}
:::
:::
